kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v1alpha2

storageConfig:
  local:
    path: /root/OC-Mirror/oc-mirror-workspace

mirror:
  platform:
    channels:
      - name: stable-4.15
        type: ocp
        minVersion: 4.15.0
        maxVersion: 4.15.0
    graph: false

  additionalImages:
    - name: quay.io/openshift-release-dev/ocp-release:4.15.0-x86_64
    # Requerida internamente por oc-mirror para construir el graph (aunque graph: false)
    - name: registry.redhat.io/ubi8/ubi-micro:latest
